GET http://localhost:3000/login

###
POST http://localhost:3000/login
Content-Type: application/json

{ "username": "Peter2021", "password": "Peter2022" }

###
POST http://localhost:3000/register
Content-Type: application/json
